name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD on push to the main branch
  pull_request:
    branches:
      - main  # Trigger CI/CD on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use the Python version your project requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job succeeds before deploying
    if: github.ref == 'refs/heads/main'  # Only deploy on the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Store your Render API key in GitHub Secrets
        run: |
          # Add commands to deploy your application to Render
          # Example: Use Render's CLI or API to deploy
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "your-service-id"}' \
            https://api.render.com/v1/services/your-service-id/deploys
